
title: Stockedgoodies
description: Ecommerce site




conf:
  disqus: Ayman

navbar:
  links:
    -
      title: Home
      url: /
    - 
      title: About
      url: /About
    - 
      title: Contact
      url: /Contact
    
      
pygments: true
permalink: none
